djangoProject3/urls.py
from django.contrib import admin
from django.urls import path
from project import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', views.get_all_products),
    path('products/<int:id>/', views.get_one_product),
    path('add/', views.add),
    path('', views.main_page),
    path('register/', views.register),
    path('login/', views.login),
    path('logout/', views.logout),
    path('add_product/', views.add_product),
]

project/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    name = models.CharField(max_length=100,
                            verbose_name='Название')

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
    title = models.CharField(max_length=100,
                             verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    price = models.IntegerField(verbose_name='Цена')
    category = models.ForeignKey(Category, null=True,
                                 on_delete=models.CASCADE,
                                 verbose_name='Категория')

    def __str__(self):
        return self.title


class Review(models.Model):
    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'
    text = models.TextField(verbose_name='Текст')
    product = models.ForeignKey(Product, null=True,
                                on_delete=models.CASCADE,
                                verbose_name='Продукт')

    def __str__(self):
        return self.text

templates/add.html
{% extends 'layout.html' %}

{% block content %}
<h1>Добавить категорию</h1>
<form action="/add/" method="post">
    {% csrf_token %}
    <label>
        <input class="form-control" type="text" placeholder="Название категории" name="category_name">
    </label>
    <input type="submit" value="Отправить">
</form>
{% endblock %}

templates/add1.html
{% extends 'layout.html' %}
{% block content %}
<h1>Добавить категорию</h1>
<form action="/add/" method="post">
    {% csrf_token %}
    {{ form }}

   <button type="submit" class="btn-info">Отправить</button>
</form>
{% endblock %}

templates/add_product.html
{% extends 'layout.html' %}

{% block content %}
<h1>
    Добавить продукт
</h1>
<form action="/add_product/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class='btn btn-danger' type="submit">Отправить</button>
</form>
{% endblock %}

templates/detail.html

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>{{ product.id }}.{{ product.title }}</h2>

{% for i in review %}
    <hr>
    <p>Отзыв продукта: {{ i.text }}</p>

{% endfor %}
    <hr>
<li>Количество отзывов товара: {{ product.title }} - {{ product.review_set.count }}</li>
     <hr>
</body>
</html>

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">GeekTech</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/admin/">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/products/">Все продукты</a>
        </li>

       {% if username %}
         <li class="nav-item">
            <a class="nav-link" href="/add/">Добавить категорию</a>

          </li>
           <li class="nav-item">
            <a class="nav-link" href="/add_product/">Добавить продукт</a>
          </li>
      {% endif %}
           <li class="nav-item">
            <a class="nav-link" href="/register/">Регистрация</a>
          </li>
       {% if username %}
            <li class="nav-item">
                <a class="nav-link" href="/logout/">Выход({{ username }})</a>
             </li>
      {% else %}
           <li class="nav-item">

            <a class="nav-link" href="/login/">Вход</a>
          </li>
          {% endif %}
      </ul>
      <form class="d-flex" action="" method="get">
        <input class="form-control me-2" name="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<div class="container" style="text-align: left">
    {% block content %}

{% endblock %}
</div>
</body>
</html>

templates/login.html
{% extends 'layout.html' %}

{% block content %}
<h1>Авторизация пользователя</h1>
    <form action="/login/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn-info">Отправить</button>
    </form>
{% endblock %}

templates/main.html
{% extends 'layout.html' %}
{% block content %}
    <h1>Главная страница</h1>
{% endblock %}

templates/products.html
{% extends 'layout.html' %}
{% block content %}
<h1 style=" color: blueviolet">Все продукты</h1>
    <hr>
{% for i in all_products %}
    <a href="/products/{{ i.id }}/">
        <p>{{ i.id }}.{{ i.title }}</p>
    </a>
    {% endfor %}
     <nav aria-label="Page navigation example">
  <ul class="pagination">
      {% for button in  buttons %}
       <li class="page-item"><a class="page-link"
                                href="/products/?page={{ button }}">{{ button }}</a>
       </li>
{% endfor %}
    </ul>
</nav>
{% endblock %}



templates/register.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Регистрация пользователя</h1>
    <form action="/register/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn-danger" type="submit">
    Зарегистрировать
    </button>
    </form>
{% endblock %}